### PR TITLE
Cosmic toplevel plugin

### PR DESCRIPTION
**Pull request by wash2**
the cosmic toplevel plugin adds support for cosmic windows as items in the launcher.

### CODE REVIEW

**Review by mmstick — DISMISSED** [review]

**Comment by mmstick** [comment]
All good. Code is highly readable and well-written.

**Comment by jacobgkau** [comment]
This does not get open windows to show up in the launcher within COSMIC Epoch on a lemp10. I've tried with both released packages and master staging packages for COSMIC. My launcher commit is on 84eb3e3.

I get this output in journalctl when I open the launcher:
```
-- Boot 3ffd86a280d9486198e7ccaf6d48326b --
Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.558 TRCE new events: epoll_fd=10, res=1
Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.558 TRCE modify: epoll_fd=10, fd=11, ev=Event { key: 18446744073709551615, readable: true, writable: false }
Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.558950Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.558 TRCE new events: epoll_fd=10, res=1
Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.558989Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.558 TRCE modify: epoll_fd=10, fd=11, ev=Event { key: 18446744073709551615, readable: true, writable: false }
Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559006Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.558 TRCE react: 1 ready wakers
Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559022Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.558 TRCE main_loop: sleeping for 50 us
Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559060Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.558 TRCE modify: epoll_fd=10, fd=9, ev=Event { key: 0, readable: true, writable: false }
Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559191Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.559 TRCE main_loop: waiting on I/O
Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559224Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.559 TRCE process_timers: 0 ready wakers
Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559244Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.559 TRCE Poller::wait(_, None)
Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559259Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.559 TRCE wait: epoll_fd=10, timeout=None
Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559276Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.559 TRCE modify: epoll_fd=10, fd=12, ev=Event { key: 18446744073709551615, readable: true, writable: false }
Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559310Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.559 TRCE block_on: sleep until notification
Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.558 TRCE react: 1 ready wakers
Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.558 TRCE main_loop: sleeping for 50 us
Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.558 TRCE modify: epoll_fd=10, fd=9, ev=Event { key: 0, readable: true, writable: false }
Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.559 TRCE main_loop: waiting on I/O
Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.559 TRCE process_timers: 0 ready wakers
Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.559 TRCE Poller::wait(_, None)
Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.559 TRCE wait: epoll_fd=10, timeout=None
Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.559 TRCE modify: epoll_fd=10, fd=12, ev=Event { key: 18446744073709551615, readable: true, writable: false }
Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.559 TRCE block_on: sleep until notification
```

The only two apps open when I'm testing right now are GNOME Terminal and Nautilus. (Interestingly, GNOME Terminal doesn't show up in the launcher's app search results in COSMIC Epoch, but it does show up in GNOME on the same machine.)

**Comment by wash2** [comment]
> This does not get open windows to show up in the launcher within COSMIC Epoch on a lemp10. I've tried with both released packages and master staging packages for COSMIC. My launcher commit is on [84eb3e3](https://github.com/pop-os/launcher/commit/84eb3e3c5072516251162abc4916b968c91e7f13).
> 
> I get this output in journalctl when I open the launcher:
> 
> ```
> -- Boot 3ffd86a280d9486198e7ccaf6d48326b --
> Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.558 TRCE new events: epoll_fd=10, res=1
> Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.558 TRCE modify: epoll_fd=10, fd=11, ev=Event { key: 18446744073709551615, readable: true, writable: false }
> Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.558950Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.558 TRCE new events: epoll_fd=10, res=1
> Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.558989Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.558 TRCE modify: epoll_fd=10, fd=11, ev=Event { key: 18446744073709551615, readable: true, writable: false }
> Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559006Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.558 TRCE react: 1 ready wakers
> Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559022Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.558 TRCE main_loop: sleeping for 50 us
> Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559060Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.558 TRCE modify: epoll_fd=10, fd=9, ev=Event { key: 0, readable: true, writable: false }
> Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559191Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.559 TRCE main_loop: waiting on I/O
> Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559224Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.559 TRCE process_timers: 0 ready wakers
> Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559244Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.559 TRCE Poller::wait(_, None)
> Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559259Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.559 TRCE wait: epoll_fd=10, timeout=None
> Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559276Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.559 TRCE modify: epoll_fd=10, fd=12, ev=Event { key: 18446744073709551615, readable: true, writable: false }
> Sep 14 16:51:43 pop-os /usr/libexec/gdm-wayland-session[2401]: 2022-09-14T22:51:43.559310Z ERROR cosmic-applet-host: cosmic_session::generic: Sep 14 22:51:43.559 TRCE block_on: sleep until notification
> Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.558 TRCE react: 1 ready wakers
> Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.558 TRCE main_loop: sleeping for 50 us
> Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.558 TRCE modify: epoll_fd=10, fd=9, ev=Event { key: 0, readable: true, writable: false }
> Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.559 TRCE main_loop: waiting on I/O
> Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.559 TRCE process_timers: 0 ready wakers
> Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.559 TRCE Poller::wait(_, None)
> Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.559 TRCE wait: epoll_fd=10, timeout=None
> Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.559 TRCE modify: epoll_fd=10, fd=12, ev=Event { key: 18446744073709551615, readable: true, writable: false }
> Sep 14 16:51:43 pop-os cosmic-session[2401]: Sep 14 22:51:43.559 TRCE block_on: sleep until notification
> ```
> 
> The only two apps open when I'm testing right now are GNOME Terminal and Nautilus. (Interestingly, GNOME Terminal doesn't show up in the launcher's app search results in COSMIC Epoch, but it does show up in GNOME on the same machine. I tried opening the launcher without Terminal open, but the Nautilus window still doesn't show up.)

It isn't one of the included plugins by default, because it isn't included in the plugins list in the justfile, but I think if you test with this it should be built and installed:
```
git clone https://github.com/wash2/launcher
cd launcher
just plugins='calc desktop_entries files find cosmic_toplevel pulse recent scripts terminal web' all
just plugins='calc desktop_entries files find cosmic_toplevel pulse recent scripts terminal web' install
```

**Comment by jacobgkau** [comment]
I see. After building locally with those options, it is working. There are a few problems:

- A GNOME Terminal window is missing its icon. This does not happen in GNOME. I assume this is related to GNOME Terminal not showing up in the app search results.

mpv-shot0079

- Selecting an open window focuses that window, but does not close the launcher; we want the launcher to close on window activation so the user can use the app.

- Even after selecting a window (which visually appears to work) and closing the launcher with ESC (which has a significant delay), keyboard input does not go to the focused window; I still need to click inside of the window before I can type into it.

- I've also noticed that in COSMIC, I need an extra down arrow key press to switch focus from the search field to the first search result; after that, I cannot return focus to the search box using the up arrow key. However, that isn't a regression in this PR.

> If we want to include it by default, i can adjust the justfile, but I left it out bc COSMIC is pre-alpha and I wanted to avoid causing any issues.

We'll need it included by default before COSMIC launches (we'll probably want it even before an internal beta), and the launcher is a big part of the COSMIC interface. This doesn't seem to break anything in a GNOME session (the open window list for GNOME still works as expected, and the regression testing checklist still passes), so it may be good to include.

**Comment by mmstick** [comment]
Yeah it should be enabled by default

**Comment by Drakulix** [comment]
> Even after selecting a window (which visually appears to work) and closing the launcher with ESC (which has a significant delay), keyboard input does not go to the focused window; I still need to click inside of the window before I can type into it.

This is a known issue of cosmic-comp (and already tracked). Keyboard focus does not return correctly after closing the launcher or app-library. I have also already figured out the cause, but a proper solution will need some refactoring.

**Comment by jacobgkau** [comment]
> This is a known issue of cosmic-comp (and already tracked).

I don't see it being tracked in https://github.com/pop-os/cosmic-comp/issues, https://github.com/pop-os/launcher/issues, or https://github.com/pop-os/cosmic-epoch/issues. Where is/was it being tracked? (I'm also unable to replicate it after the latest COSMIC updates and on the latest commit from this PR, but not sure if that's a temporary coincidence or not.)

The package built from a6f8973 still doesn't have the plugin working by default; building locally using the `just` commands still gets it working.

**Review by mmstick — DISMISSED** [review]

**Comment by wash2** [comment]
> The package still doesn't have the plugin working by default; building locally using the just commands still gets it working. 

This still seems to be an issue with the current commit

**Comment by mmstick** [comment]
The link has to be added to https://github.com/pop-os/launcher/blob/master/debian/pop-launcher.links

**Review by mmstick — APPROVED** [review]

**Comment by jacobgkau** [comment]
This is failing to build.

```
    Updating git repository `https://github.com/pop-os/cosmic-protocols`
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  failed to select a version for the requirement `serde_with = "^2.0.1"`
  candidate versions found which didn't match: 1.14.0, 1.13.0, 1.12.1, ...
  location searched: crates.io index
  required by package `pop-launcher v1.2.2 (/home/jacob/Work/launcher)`
make[1]: Leaving directory '/home/jacob/Work/launcher'
   dh_clean
 debian/rules build
dh build --with=systemd
   dh_update_autotools_config
   dh_autoreconf
   debian/rules override_dh_auto_build
make[1]: Entering directory '/home/jacob/Work/launcher'
env CARGO_HOME="$(pwd)/target/cargo" just rootdir=debian/tmp debug=0 vendor=1
cargo build -p pop-launcher-bin --frozen --offline --release
error: failed to get `cosmic-client-toolkit` as a dependency of package `pop-launcher-plugins v1.2.2 (/home/jacob/Work/launcher/plugins)`

Caused by:
  failed to load source for dependency `cosmic-client-toolkit`

Caused by:
  Unable to update https://github.com/pop-os/cosmic-protocols#1615d904

Caused by:
  can't checkout from 'https://github.com/pop-os/cosmic-protocols': you are in the offline mode (--offline)
error: Recipe `all` failed on line 38 with exit code 101
make[1]: *** [debian/rules:28: override_dh_auto_build] Error 101
make[1]: Leaving directory '/home/jacob/Work/launcher'
make: *** [debian/rules:9: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

**Comment by wash2** [comment]
Ok builds should be fixed again. I cleanup up the dependencies in the plugin, and added the missing items from Build-Depends.

**Review by jacobgkau — CHANGES_REQUESTED** [review]
This gets open windows in COSMIC showing up in the Launcher, both by default and via search. I had to restart the session for this to start working after installing the update.

However, in a classic Pop (GNOME) session, this PR adds a noticeable delay between opening the launcher and seeing open windows in the list.

https://user-images.githubusercontent.com/7199422/215191700-341b50aa-e2ca-49fc-a5d7-067ded0a1b3f.mp4

The delay also prevents me from searching for anything (including apps that aren't currently open) until the loading is complete. I also see a lag between updating a search string and seeing the results updated.

**Comment by wash2** [comment]
I noticed this as well. I'll see if I can make it cause less of a delay when not using COSMIC.

**Comment by wash2** [comment]
Ok the delay should be fixed

**Review by jacobgkau — APPROVED** [review]
Testing 489838d, there is no longer a delay in GNOME. Open windows are still shown in both GNOME and COSMIC.

<details>
<summary>Regression testing passed:</summary>

- [X] All windows on all workspaces appear on launch
- [X] Choosing an app on another workspace moves workspaces and focus to that app
- [X] Launching an application works
- [X] Typing text and then removing it will re-show those windows
- [X] Search works for applications and windows
- [X] Search works for GNOME settings panels
- [X] Search for "Extensions". There should be only one entry.
- [X] The overlay hint correctly highlights the selected window
- [X] Open windows are sorted above applications (e.g. "firefox")
- [X] t: executes a command in a terminal
- [X] : executes a command in sh
- [X] = calculates an equation
- [X] Search results are as expected:
    - `cal` returns Calendar and Calculator before Color
    - `pops` returns Popsicle first
    - `shop` returns the Pop!_Shop first
</details>

**Review by mmstick — APPROVED** [review]

**Pull request merged**
