### PR TITLE
1.2.0: Launcher improvements

### LINKED ISSUE #60: Calculator: entering "1pass" displays math result above 1Password app result
OS: 21.04

Typing "system76" into the Launcher now suggests the #1 result is "= approx. 206.58942 ug^2 / kPa"

Kind of a fun easter egg but I figure since it's your brand name may be worth fixing.

edit (added a screenshot)

Screenshot from 2021-11-12 06-09-23

### LINKED ISSUE #92: Web plugin breaks http links
I noticed that the web plugin always tries to use https even when supplied with a link that uses http. I have a situation where I want to use the launcher to quickly access a server on my local host, which uses http but the plugin adds https in front of it, thus, breaking the link. I would be thankful to see this issue fixed.

### LINKED ISSUE #94: Launcher Calculator
**(1) Issue/Bug Description:**
When you use the Launcher Calculator, there is a small bug that makes the calculator to ignore the negative symbol.
This happens when you are using the negative symbol from a previous result at the calculator, and the problem is that the negative symbol that the calculator detects is different to the one from the calculator output.

**(2) Steps to reproduce (if you know):**
-100+90
Click enter and you will have
= −10
Now, if you add +1:
= −10+1
= 11
You can visually see that the first negative symbol - is not the same as the one from the output −, so probably, the calculator does not detect the symbol.

**(3) Expected behavior:**
 -100+90
= -10
= -10 + 1
= -9

**(4) Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
GNOME Shell 40.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

pop-shell:
  Installed: 1.1.0 ~ 1648206495 ~ 21.10 ~ 28c3a18
  Candidate: 1.1.0 ~ 1648206495 ~ 21.10 ~ 28c3a18
  Version table:
 *** 1.1.0 ~ 1648206495 ~ 21.10 ~ 28c3a18 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status

**(7) Where was Pop Shell installed from:**
Basic Pop!_OS installation

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2 x 1080p, Horizontal

**(9) Other Installed/Enabled Extensions:**
-

**(10) Other Notes:**
-

### PR DESCRIPTION
**Pull request by mmstick**
- Handle unicode minus sign codes in qalc
- Switched from smol-rs to tokio
- Switched from isahc to reqwest
- Get recent files from `recently-used-xbel` instead of GTK
- GTK is now no longer a required build or runtime dependency
- Significantly reduces dynamic linking
- Switched from Makefile to justfile
- Updated dependencies
- Only calculate queries that start with numbers or `-`
- Fix http link support for the web plugin
- Improves display of found files by stripping any leading `./` from paths
- Adds optional logging support for pop-shell's plugins

Closes #94 
Closes #92
Closes #60

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
Another issue, the calculator plugin seems broken (with or without the prefix):

Screenshot from 2022-03-28 11-29-26
Screenshot from 2022-03-28 11-29-33

**Comment by jacobgkau** [comment]
Calculator is working again now. Recents order looks good, but now that the number's been increased, the launcher is hitting the edge of the display/overlapping the dock:

Screenshot from 2022-03-28 14-38-01

Scrolling behavior's also a little confusing without a visible scrollbar. Might be best to keep it limited to 8 for now, unless we want to hash out the UX for a larger result set (the current limit was implemented intentionally in May 2021, from what I can see.)

**Comment by mmstick** [comment]
Sure, I'll remove those commits.

**Review by jacobgkau — APPROVED** [review]
Confirmed all three issues in the description are fixed. Calculator & recents are both working as expected now. Regression testing passed:
[launcher-pr95-impish.txt](https://github.com/pop-os/launcher/files/8366630/launcher-pr95-impish.txt)
[launcher-pr95-focal.txt](https://github.com/pop-os/launcher/files/8366874/launcher-pr95-focal.txt)

**Pull request merged**
