### PR TITLE
chore: Update dependencies

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
This seems to build locally, but failed to build for all releases on the build server:
<details>
<summary>Output:</summary>

```
[1mlauncher: 6bd9b7aa4659bfb570f181d7aa03de6f1484f1c5 (launcher): impish (21.10): source github status pending[0m
 dpkg-buildpackage -d -us -uc -ui -S
dpkg-buildpackage: info: source package pop-launcher
dpkg-buildpackage: info: source version 1.1.0~1646067958~21.10~6bd9b7a
dpkg-buildpackage: info: source distribution impish
dpkg-buildpackage: info: source changed by Pop OS (ISO Signing Key) <info@system76.com>
 dpkg-source --before-build .
 fakeroot debian/rules clean
dh clean --with=systemd
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/home/jenkins/workspace/pop-os/repos/_build/ci/git/launcher/6bd9b7aa4659bfb570f181d7aa03de6f1484f1c5/impish/partial.source/archive'
ischroot && make clean || make distclean
make[2]: Entering directory '/home/jenkins/workspace/pop-os/repos/_build/ci/git/launcher/6bd9b7aa4659bfb570f181d7aa03de6f1484f1c5/impish/partial.source/archive'
rm -rf .cargo vendor vendor.tar target
make[2]: Leaving directory '/home/jenkins/workspace/pop-os/repos/_build/ci/git/launcher/6bd9b7aa4659bfb570f181d7aa03de6f1484f1c5/impish/partial.source/archive'
ischroot || make vendor
make[2]: Entering directory '/home/jenkins/workspace/pop-os/repos/_build/ci/git/launcher/6bd9b7aa4659bfb570f181d7aa03de6f1484f1c5/impish/partial.source/archive'
mkdir -p .cargo
cargo vendor --sync plugins/Cargo.toml | head -n -1 > .cargo/config
error: failed to sync

Caused by:
  failed to download packages

Caused by:
  failed to download `atk v0.15.1`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/atk-0.15.1/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
echo 'directory = "vendor"' >> .cargo/config
tar pcf vendor.tar vendor
rm -rf vendor
```
</pre>
</details>

**Comment by mmstick** [comment]
Sounds like the build server has an older version of Rust installed. Maybe it needs an update?

**Comment by jackpot51** [comment]
@mmstick if you need a specific version, please add a rust-toolchain file.

**Review by jacobgkau — CHANGES_REQUESTED** [review]
After this change, selecting open windows (with Enter or click) no longer works. If I'm trying to select the window that's highlighted, then its highlight goes away, but that's it. The window is not focused and the launcher does not close. (Opening new apps appears to be unaffected.)

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Confirmed a .desktop file in `/usr/local/share/applications/` shows up now.

Launcher regression testing passed:
[launcher-pr87-impish.txt](https://github.com/pop-os/launcher/files/8163145/launcher-pr87-impish.txt)
[launcher-pr87-focal.txt](https://github.com/pop-os/launcher/files/8163336/launcher-pr87-focal.txt)

**Pull request merged**
